--add some useful indexes to the local db.

CREATE INDEX AWARD_PROPOSAL_SPONSOR_ID_I ON AWARD_PROPOSAL (AWARD_PROP_SPONSOR_ID);

CREATE UNIQUE INDEX SPONSOR_ABBREVIATION_I ON SPONSOR_T (SPONSOR_ABBREVIATION);

CREATE INDEX PROJECT_MEMBERS_ID_I ON PROJECT_MEMBERS_T (PROJECT_ID_C);
CREATE INDEX PROJECT_MEMBERS_AWARD_PROPOSAL_I ON PROJECT_MEMBERS_T (AWARD_PROPOSAL_C);
CREATE INDEX PROJECT_MEMBERS_INVESTIGATOR_ID_I ON PROJECT_MEMBERS_T (INVESTIGATOR_ID_C);
