--drop tables created by ospindexcreate.sql

ALTER  TABLE OSPLOCAL.AWARD_PROPOSAL DROP INDEX AWARD_PROPOSAL_SPONSOR_ID_I;
ALTER  TABLE OSPLOCAL.SPONSOR_T DROP SPONSOR_ABBREVIATION_I;
ALTER  TABLE PROJECT_MEMBERS_T DROP INDEX PROJECT_MEMBERS_ID_I;
ALTER  TABLE PROJECT_MEMBERS_T DROP INDEX PROJECT_MEMBERS_AWARD_PROPOSAL_I;
ALTER  TABLE PROJECT_MEMBERS_T DROP INDEX PROJECT_MEMBERS_INVESTIGATOR_ID_I;
