-- bcaruso drop local tables
-- 2004-12-08

DROP TABLE OSPLOCAL.AWARD_PROPOSAL;
DROP TABLE OSPLOCAL.INVESTIGATORS_T;
DROP TABLE OSPLOCAL.PROJECT_MEMBERS_T;
DROP TABLE OSPLOCAL.DEPARTMENT_T;
DROP TABLE OSPLOCAL.SPONSOR_T;

