-- DDL statements to create the osp database in MySQL

--  extracted from cudmtest.dataserver.cornell.edu
--  on 2004-12-06 with dbDesigner v4 
--  bdc34@cornell.edu

-- Based on OSPWH.AWARD_PROPOSAL
CREATE TABLE osplocal.AWARD_PROPOSAL (
AWARD_PROP_PROJECT_ID	VARCHAR(6),
AWARD_PROPOSAL_ID	VARCHAR(4),
AWARD_OR_PROPOSAL	VARCHAR(8),
AWARD_PROP_TITLE	VARCHAR(200),
AWARD_PROP_FULL_TITLE	VARCHAR(255),
AWARD_PROP_STATUS	VARCHAR(50),
AWARD_PROP_STATUS_CODE	VARCHAR(5),
-- AWARD_PROP_GCO_ID	NUMERIC,
-- AWARD_PROP_GCO_NAME	VARCHAR(100),
-- AWARD_PROP_PI_ID	NUMERIC,
-- AWARD_PROP_PI_NAME	VARCHAR(100),
-- AWARD_PROP_PI_NETID	VARCHAR(20),
-- AWARD_PROP_PI_DEPT	VARCHAR(50),
-- AWARD_PROP_PROJ_DIRECTOR_ID	NUMERIC,
-- AWARD_PROP_PROJ_DIRECTOR_NAME	VARCHAR(100),
-- AWARD_PROP_PROJ_DIRECTOR_NETID	VARCHAR(20),
-- AWARD_PROP_PROJ_DIRECTOR_DEPT	VARCHAR(50),
AWARD_PROP_COLLEGE	VARCHAR(100),
AWARD_PROP_DEPARTMENT_ID	NUMERIC,
-- AWARD_PROP_DEPARTMENT	VARCHAR(50),
-- AWARD_PROP_DEPARTMENT_ADW_CODE	VARCHAR(3),
-- AWARD_PROP_SPONSOR_NAME	VARCHAR(150),
-- AWARD_PROP_SPONSOR_ALL_LEVELS	VARCHAR(100),
AWARD_PROP_SPONSOR_ID	NUMERIC,  
-- AWARD_PROP_PROGRAM_ID	NUMERIC,
-- AWARD_PROP_PROGRAM_NAME	VARCHAR(100),
-- SPONSOR_MODIFICATION_NUMERIC	VARCHAR(15),
SPONSOR_PROJECT_ID	VARCHAR(28), -- the id that the sponsor uses
-- AWARD_PROP_CFDA_NUMERIC	VARCHAR(7),
-- AWARD_PROP_FUNCTION_CD	CHAR(1),
-- AWARD_PROP_FUNCTION	VARCHAR(50),
AWARD_PROP_START_DATE	DATE,
AWARD_PROP_END_DATE	DATE,
AWARD_PROP_TOTAL	NUMERIC,
AWARD_PROP_BUDGET_START_DATE DATE,
AWARD_PROP_BUDGET_END_DATE	DATE,
AWARD_PROP_BUDGET_TOTAL	NUMERIC,
-- AWARD_PROP_A133_REQUIRED	CHAR(1),
-- AWARD_PROP_ARCHIVE_LOCATION	VARCHAR(6),
-- AWARD_PROP_ARCHIVE_RETENTION	NUMERIC,
-- AWARD_PROP_HAS_CONSULT_AGRMTS	CHAR(1),
-- AWARD_PROP_HAS_SUBCONTRACTS	CHAR(1),
-- AWARD_PROP_SHIPPING_TYPE	VARCHAR(20),
AWARD_DESCRIPTION	VARCHAR(30), -- grant, fixed, coop, cost
-- AWARD_DESCRIPTION_CODE	CHAR(1),
-- AWARD_REVIEWED_BY	VARCHAR(255),
-- AWARD_REVIEWED_BY_DATE	DATE,
-- AWARD_APPROVED_BY	VARCHAR(255),
-- AWARD_APPROVED_BY_DATE	DATE,
-- AWARD_DISTRIBUTED_BY	VARCHAR(255),
-- AWARD_DISTRIBUTED_BY_DATE	DATE,
PROPOSAL_PURPOSE	VARCHAR(30),
PROPOSAL_PURPOSE_DESCRIPTION	VARCHAR(80),
-- PROPOSAL_DEADLINE_DATE	DATE,
-- PROPOSAL_DEADLINE_TYPE	CHAR(1),
-- PROPOSAL_SENT_DATE	DATE,
-- EQUIPMENT_OWNER	VARCHAR(20),
-- EQUIPMENT_PURCHASE	CHAR(1),
-- PERSONNEL_SPACE	CHAR(1),
-- PLOTS_LANDS_PONDS	CHAR(1),
-- RENOVATION_CONSTRUCTION	CHAR(1),
-- UTILITY_NETWORK_SERVICES	CHAR(1),
-- FA_ABOVE_LINE	VARCHAR(5),
-- FA_ABOVE_LINE_REASON	VARCHAR(60),
-- FA_BASE	VARCHAR(5),
-- FA_BASE_OTHER_DESC	VARCHAR(60),
-- FA_COSTS_NOT_FULL_RATE_EXPL	VARCHAR(200),
-- FA_DIRECT_CHARGE_ADMIN	CHAR(1),
-- FA_DIRECT_CHARGE_MEMBERSHIP	CHAR(1),
-- FA_DIRECT_CHARGE_POSTAGE	CHAR(1),
-- FA_DIRECT_CHARGE_SUPPLIES	CHAR(1),
-- FA_DIRECT_CHARGE_TELEPHONE	CHAR(1),
-- FA_REASON	VARCHAR(50),
-- MAND_CENTER_COST_SHARING	NUMERIC,
-- MAND_COLLEGE_COST_SHARING	NUMERIC,
-- MAND_DEPARTMENT_COST_SHARING	NUMERIC,
-- MAND_EXTERNAL_COST_SHARING	NUMERIC,
-- MAND_UNIVERSITY_COST_SHARING	NUMERIC,
-- VOL_CENTER_COST_SHARING	NUMERIC,
-- VOL_COLLEGE_COST_SHARING	NUMERIC,
-- VOL_DEPARTMENT_COST_SHARING	NUMERIC,
-- VOL_EXTERNAL_COST_SHARING	NUMERIC,
-- VOL_UNIVERSITY_COST_SHARING	NUMERIC,
FEDERAL_FLOW_THROUGH	CHAR(1),
FLOW_THROUGH_SPONS_ALL_LEVELS	VARCHAR(100),
FLOW_THROUGH_SPONSOR_ID	NUMERIC,
FLOW_THROUGH_SPONSOR_NAME	VARCHAR(150),
-- FIRST_AWARD_DATE	DATE,
-- LAST_AWARD_OR_AMEND_DATE	DATE,
-- SHIPPING_COMMENT	VARCHAR(100),
-- SHIPPING_METHOD	VARCHAR(80),
AWARD_PROP_UPDATE_DATE	DATE,
-- AWARD_PROP_UPDATE_NETID	VARCHAR(20),
-- COST_SHARING_TOTAL	NUMERIC,
-- RESTRICTED_ACCESS_DATA_SETS	CHAR(1),
-- AWARD_PROP_BUDGET_COMMENT	VARCHAR(255),
-- AWARD_PROP_IP_AGREEMENT	CHAR(1),
-- B_MAND_DEPARTMENT_COST_SHARING	NUMERIC,
-- B_MAND_CENTER_COST_SHARING	NUMERIC,
-- B_MAND_COLLEGE_COST_SHARING	NUMERIC,
-- B_MAND_UNIVERSITY_COST_SHARING	NUMERIC,
-- B_MAND_EXTERNAL_COST_SHARING	NUMERIC,
-- B_VOL_DEPARTMENT_COST_SHARING	NUMERIC,
-- B_VOL_CENTER_COST_SHARING	NUMERIC,
-- B_VOL_COLLEGE_COST_SHARING	NUMERIC,
-- B_VOL_UNIVERSITY_COST_SHARING	NUMERIC,
-- B_VOL_EXTERNAL_COST_SHARING	NUMERIC,
-- AWARD_PROP_PI_CORNELL_ID	VARCHAR(11),
-- AWARD_PROP_PROJ_DIR_CORNELL_ID	VARCHAR(11),

--the following were added by bdc34 and were not part of OSPWH.AWARD_PROPOSAL
BEST_GUESS_START_DATE DATE,
BEST_GUESS_END_DATE DATE,
CONSTRAINT AWARD_PROP_PK PRIMARY KEY (AWARD_PROP_PROJECT_ID, AWARD_PROPOSAL_ID)
);



-- replaces investigator_project and co_pi
CREATE TABLE osplocal.INVESTIGATORS_T (
  INVPROJ_INVESTIGATOR_ID NUMERIC NOT NULL, -- PK
  INVPROJ_FULL_NAME VARCHAR(100) NOT NULL,
  INVPROJ_FIRST_NAME VARCHAR(30) ,
  INVPROJ_MIDDLE_NAME VARCHAR(30),
  INVPROJ_LAST_NAME VARCHAR(50),
  INVPROJ_INVESTIGATOR_NETID VARCHAR(20) NOT NULL,
  INVPROJ_DEPT_ID NUMERIC,
  INVPROJ_UPDATE_DATE DATE,
  INVPROJ_EMAIL_ADDRESS VARCHAR(50), 
  INVPROJ_UPDATE_NETID VARCHAR(20),

CONSTRAINT INVESTIGATOR_T_PK PRIMARY KEY (INVPROJ_INVESTIGATOR_ID)
);

CREATE TABLE osplocal.PROJECT_MEMBERS_T (
	INVESTIGATOR_ID_C NUMERIC NOT NULL,		-- PK
	PROJECT_ID_C VARCHAR (6) NOT NULL,		-- PK
	AWARD_PROPOSAL_C VARCHAR (4) NOT NULL,	-- PK
	DEPARTMENT_ID_C NUMERIC NOT NULL,
	ROLE_C CHAR(2)
--CONSTRAINT PROJECT_MEMBERS_T_PK PRIMARY KEY (INVESTIGATOR_ID_C, PROJECT_ID_C, AWARD_PROPOSAL_C)
);

CREATE TABLE osplocal.DEPARTMENT_T (
  DEPARTMENT_ID NUMERIC NOT NULL,
  DEPARTMENT_NAME VARCHAR(50) NOT NULL,
  DEPARTMENT_ABBREVIATION VARCHAR(25),
  DEPARTMENT_COLLEGE_NAME VARCHAR(100),
  DEPARTMENT_COLLEGE_CODE NUMERIC,

CONSTRAINT DEPARTMENT_T_PK PRIMARY KEY (DEPARTMENT_ID)
);

-- sponsor_t is based on OSPWH.SPONSOR
CREATE TABLE osplocal.SPONSOR_T (
  SPONSOR_ID NUMERIC NOT NULL,
  SPONSOR_NAME VARCHAR(150) NOT NULL,
  SPONSOR_ALL_LEVELS VARCHAR(100) ,
  SPONSOR_LEVEL_1 VARCHAR(30) , -- levels might be SPONSOR_ABBREVIATION
  SPONSOR_LEVEL_2 VARCHAR(30) ,
  SPONSOR_LEVEL_3 VARCHAR(30) ,
  SPONSOR_ABBREVIATION VARCHAR(30) ,
--   SPONSOR_ORIGIN_CD CHAR NOT NULL,  
  SPONSOR_ORIGIN VARCHAR(20) , -- american or forigen
--   SPONSOR_FUND_SOURCE_CODE VARCHAR( NOT NULL,
  SPONSOR_FUND_SOURCE VARCHAR(30), -- NPO, University, corp. gov etc.
  SPONSOR_EMAIL_ADDRESS VARCHAR(50),
  SPONSOR_WEB_SITE VARCHAR(100) ,
  SPONSOR_STREET_1 VARCHAR(60) ,
  SPONSOR_STREET_2 VARCHAR(60) ,
  SPONSOR_CITY VARCHAR(40) ,
  SPONSOR_STATE VARCHAR(20) ,
  SPONSOR_COUNTRY VARCHAR(30),
  SPONSOR_ZIP_CODE VARCHAR(20),
--   REQUIRES_FULL_A133_REPORT CHAR NOT NULL,
--   SPONSOR_A133_REQUIRED CHAR NOT NULL,
  SPONSOR_LEVEL CHAR (2),
  SPONSOR_PARENT_ID NUMERIC,
--   SPONSOR_STATUS CHAR NOT NULL,
--   SPONSOR_UPDATE_DATE DATE NOT NULL,
--   SPONSOR_UPDATE_NETID INTEGER NOT NULL,
--   SPONSOR_NAME_AND_ALL_LEVELS INTEGER NOT NULL,
--   HIGH_RISK CHAR NOT NULL,
--   A133_FIRST_NAME INTEGER NOT NULL,
--   A133_LAST_NAME INTEGER NOT NULL,
--   A133_EMAIL INTEGER NOT NULL,
--   A133_ADDRESS_1 INTEGER NOT NULL,
--   A133_ADDRESS_2 INTEGER NOT NULL,
--   A133_CITY INTEGER NOT NULL,
--   A133_STATE INTEGER NOT NULL,
--   A133_ZIP INTEGER NOT NULL,
--   A133_LAST_UPDATE_DATE DATE NOT NULL,

CONSTRAINT SPONSOR_T_PK PRIMARY KEY (SPONSOR_ID)
);

