select 
AWARD_APPROVED_BY_DATE,
AWARD_DISTRIBUTED_BY_DATE,
AWARD_PROP_BUDGET_END_DATE,		--primary date
AWARD_PROP_BUDGET_START_DATE,	--primary date
AWARD_PROP_END_DATE,			--secondary date
AWARD_PROP_START_DATE,			--secondary date
AWARD_PROP_UPDATE_DATE,			--fallback date
AWARD_PROP_UPDATE_NETID,
AWARD_REVIEWED_BY_DATE,
FIRST_AWARD_DATE,
LAST_AWARD_OR_AMEND_DATE,
PROPOSAL_DEADLINE_DATE,
PROPOSAL_SENT_DATE 
from ospwh.award_proposal
WHERE AWARD_PROP_COLLEGE LIKE 'AGRICULTURE & LIFE SCIENCES' 